import Head from 'next/head';
import Header from '@/components/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Header*/}

      <Header />

      <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere
        necessitatibus molestias ab. Molestias numquam amet omnis expedita
        perspiciatis error, suscipit provident facere sunt tempora possimus ex,
        totam sint, rerum praesentium. Numquam veniam obcaecati sed, alias, quo
        ipsum quam sapiente culpa in amet quaerat? At, quis fugiat. At dicta
        porro dolore. Quod vel dolore rerum ipsam eaque illum ratione iusto
        incidunt. Reprehenderit adipisci, consequuntur corrupti excepturi neque
        recusandae quis nobis. Necessitatibus quidem, animi, non ab vero eum
        quae nam, recusandae architecto accusamus aliquid unde beatae ipsa
        earum? Quisquam sint illo ut! Ut cumque provident vitae a atque mollitia
        eum excepturi harum sunt officia eaque ducimus repudiandae qui
        consequuntur, voluptate beatae, iusto assumenda. Quam necessitatibus
        excepturi aperiam aliquam ad culpa laudantium obcaecati? Quos voluptatem
        unde fugiat quis consectetur eius blanditiis aliquam tempore culpa?
        Officiis natus cumque nulla, consequatur iure quaerat inventore quod,
        iusto fuga accusamus enim porro optio nesciunt cupiditate blanditiis
        illum! Neque ipsam, numquam earum architecto harum tempora, corporis
        temporibus perspiciatis tenetur quisquam error. Impedit accusamus
        officiis natus doloribus reiciendis repellendus vero corporis, sunt
        illum earum omnis aut dolor iusto molestiae! Voluptatem ex dolore
        tenetur eveniet error et possimus at necessitatibus aspernatur facilis
        officiis asperiores unde, laborum architecto pariatur? Laboriosam rem
        eius nisi nulla in voluptatum quibusdam animi. Repellat, saepe
        quibusdam. Libero rem modi, fugiat culpa voluptate dolorum minus, soluta
        officiis nihil id maxime odio quis a et minima in exercitationem. Quae
        magnam temporibus asperiores sit fugit placeat, consequatur accusamus
        est! Nisi distinctio vel accusantium, quo dolorem nesciunt ex corporis
        sit error libero laboriosam? Earum ad neque iusto quidem adipisci
        impedit ipsum voluptas, asperiores magnam porro odio ipsam odit illo
        error? Quas asperiores perspiciatis eum harum blanditiis dolores
        cupiditate sint! Numquam eos excepturi error soluta, temporibus ipsum
        unde aperiam atque obcaecati animi accusamus qui. Nam voluptatum
        voluptas consequatur temporibus fugit mollitia!
      </div>

      {/*Feed*/}

      {/*Modal*/}
    </>
  );
}
