import Head from 'next/head';
import Header from './Header';

export default function Layout({ children }) {
  return (
    <div className="bg-gray-200 min-h-screen">
      <Head>
        <title>InstaAlien</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </div>
  );
}
